spring:
  redis:
    timeout: 15000  #连接超时时间
    password: pwd  #密碼
    cluster:
      max-redirects: 6   # 获取失败 最大重定向次数
      nodes:  #Redis集群的节点
        - 47.97.118.22:7000
        - 47.97.118.22:7001
        - 47.97.118.22:7002
        - 47.97.118.22:7003
        - 47.97.118.22:7004
        - 47.97.118.22:7005
    lettuce:  #连接池使用lettuce lettuce主要利用netty实现与redis的同步和异步通信可多个线程间并发访问，是线程安全的 jedis在多线程环境下是非线程安全的
      pool:
        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
